/*
 * Matrix Routing
 *
 * With the Matrix Routing service you can compute distances and travel times between a set of origins and destinations.
 *
 * The version of the OpenAPI document: 1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.matrixrouting.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.matrixrouting.Model
{
    /// <summary>
    /// MatrixResponse
    /// </summary>
    [DataContract(Name = "MatrixResponse")]
    public partial class MatrixResponse : IEquatable<MatrixResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MatrixResponse" /> class.
        /// </summary>
        /// <param name="percentageOfDirectDistanceRelations">Percentage of relations in the distance matrix which has not been calculated successfully.  Zero distances corresponding to A-A relations are not included in this calculation..</param>
        /// <param name="distances">The distances of the requested matrix elements [m]. To access to the distance of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the distance for an A-A relation is always set to zero..</param>
        /// <param name="distancesEncoded">The distances of the requested matrix elements [m]. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information. To access to the distance of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the distance for an A-A relation is always set to zero..</param>
        /// <param name="travelTimes">The travel times of the requested matrix elements [s]. To access to the travel time of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the travel time for an A-A relation is always set to zero..</param>
        /// <param name="travelTimesEncoded">The travel times of the requested matrix elements [s]. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information. To access to the travel time of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the travel time for an A-A relation is always set to zero..</param>
        /// <param name="travelTimeProfilesEncoded">The travel time profiles of the requested matrix elements. Each profile is expressed using a encoded format which is explained [here](./documentation/matrix-routing-api/concepts/results-representation).  Please note that the travel time for an A-A relation is always set to zero..</param>
        /// <param name="tollCosts">The toll costs of the requested matrix elements in the requested currency. To access to the toll cost of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations.   Toll prices do not include VAT. .</param>
        /// <param name="tollCostsEncoded">The toll costs of the requested matrix elements in the requested currency. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information. To access to the toll cost of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the travel time for an A-A relation is always set to zero..</param>
        /// <param name="warnings">A list of warnings concerning the validity of the result..</param>
        public MatrixResponse(double percentageOfDirectDistanceRelations = default(double), List<int> distances = default(List<int>), byte[] distancesEncoded = default(byte[]), List<int> travelTimes = default(List<int>), byte[] travelTimesEncoded = default(byte[]), byte[] travelTimeProfilesEncoded = default(byte[]), List<double> tollCosts = default(List<double>), byte[] tollCostsEncoded = default(byte[]), List<Warning> warnings = default(List<Warning>))
        {
            this.PercentageOfDirectDistanceRelations = percentageOfDirectDistanceRelations;
            this.Distances = distances;
            this.DistancesEncoded = distancesEncoded;
            this.TravelTimes = travelTimes;
            this.TravelTimesEncoded = travelTimesEncoded;
            this.TravelTimeProfilesEncoded = travelTimeProfilesEncoded;
            this.TollCosts = tollCosts;
            this.TollCostsEncoded = tollCostsEncoded;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Percentage of relations in the distance matrix which has not been calculated successfully.  Zero distances corresponding to A-A relations are not included in this calculation.
        /// </summary>
        /// <value>Percentage of relations in the distance matrix which has not been calculated successfully.  Zero distances corresponding to A-A relations are not included in this calculation.</value>
        [DataMember(Name = "percentageOfDirectDistanceRelations", EmitDefaultValue = false)]
        public double PercentageOfDirectDistanceRelations { get; set; }

        /// <summary>
        /// The distances of the requested matrix elements [m]. To access to the distance of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the distance for an A-A relation is always set to zero.
        /// </summary>
        /// <value>The distances of the requested matrix elements [m]. To access to the distance of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the distance for an A-A relation is always set to zero.</value>
        [DataMember(Name = "distances", EmitDefaultValue = false)]
        public List<int> Distances { get; set; }

        /// <summary>
        /// The distances of the requested matrix elements [m]. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information. To access to the distance of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the distance for an A-A relation is always set to zero.
        /// </summary>
        /// <value>The distances of the requested matrix elements [m]. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information. To access to the distance of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the distance for an A-A relation is always set to zero.</value>
        [DataMember(Name = "distancesEncoded", EmitDefaultValue = false)]
        public byte[] DistancesEncoded { get; set; }

        /// <summary>
        /// The travel times of the requested matrix elements [s]. To access to the travel time of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the travel time for an A-A relation is always set to zero.
        /// </summary>
        /// <value>The travel times of the requested matrix elements [s]. To access to the travel time of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the travel time for an A-A relation is always set to zero.</value>
        [DataMember(Name = "travelTimes", EmitDefaultValue = false)]
        public List<int> TravelTimes { get; set; }

        /// <summary>
        /// The travel times of the requested matrix elements [s]. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information. To access to the travel time of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the travel time for an A-A relation is always set to zero.
        /// </summary>
        /// <value>The travel times of the requested matrix elements [s]. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information. To access to the travel time of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the travel time for an A-A relation is always set to zero.</value>
        [DataMember(Name = "travelTimesEncoded", EmitDefaultValue = false)]
        public byte[] TravelTimesEncoded { get; set; }

        /// <summary>
        /// The travel time profiles of the requested matrix elements. Each profile is expressed using a encoded format which is explained [here](./documentation/matrix-routing-api/concepts/results-representation).  Please note that the travel time for an A-A relation is always set to zero.
        /// </summary>
        /// <value>The travel time profiles of the requested matrix elements. Each profile is expressed using a encoded format which is explained [here](./documentation/matrix-routing-api/concepts/results-representation).  Please note that the travel time for an A-A relation is always set to zero.</value>
        [DataMember(Name = "travelTimeProfilesEncoded", EmitDefaultValue = false)]
        public byte[] TravelTimeProfilesEncoded { get; set; }

        /// <summary>
        /// The toll costs of the requested matrix elements in the requested currency. To access to the toll cost of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations.   Toll prices do not include VAT. 
        /// </summary>
        /// <value>The toll costs of the requested matrix elements in the requested currency. To access to the toll cost of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations.   Toll prices do not include VAT. </value>
        [DataMember(Name = "tollCosts", EmitDefaultValue = false)]
        public List<double> TollCosts { get; set; }

        /// <summary>
        /// The toll costs of the requested matrix elements in the requested currency. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information. To access to the toll cost of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the travel time for an A-A relation is always set to zero.
        /// </summary>
        /// <value>The toll costs of the requested matrix elements in the requested currency. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information. To access to the toll cost of the relation between the origin i and the destination j, read the k-th element defined by &#x60;k &#x3D; i * N + j&#x60;, with N being the number of destinations. Please note that the travel time for an A-A relation is always set to zero.</value>
        [DataMember(Name = "tollCostsEncoded", EmitDefaultValue = false)]
        public byte[] TollCostsEncoded { get; set; }

        /// <summary>
        /// A list of warnings concerning the validity of the result.
        /// </summary>
        /// <value>A list of warnings concerning the validity of the result.</value>
        [DataMember(Name = "warnings", EmitDefaultValue = false)]
        public List<Warning> Warnings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MatrixResponse {\n");
            sb.Append("  PercentageOfDirectDistanceRelations: ").Append(PercentageOfDirectDistanceRelations).Append("\n");
            sb.Append("  Distances: ").Append(Distances).Append("\n");
            sb.Append("  DistancesEncoded: ").Append(DistancesEncoded).Append("\n");
            sb.Append("  TravelTimes: ").Append(TravelTimes).Append("\n");
            sb.Append("  TravelTimesEncoded: ").Append(TravelTimesEncoded).Append("\n");
            sb.Append("  TravelTimeProfilesEncoded: ").Append(TravelTimeProfilesEncoded).Append("\n");
            sb.Append("  TollCosts: ").Append(TollCosts).Append("\n");
            sb.Append("  TollCostsEncoded: ").Append(TollCostsEncoded).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MatrixResponse);
        }

        /// <summary>
        /// Returns true if MatrixResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of MatrixResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MatrixResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PercentageOfDirectDistanceRelations == input.PercentageOfDirectDistanceRelations ||
                    this.PercentageOfDirectDistanceRelations.Equals(input.PercentageOfDirectDistanceRelations)
                ) && 
                (
                    this.Distances == input.Distances ||
                    this.Distances != null &&
                    input.Distances != null &&
                    this.Distances.SequenceEqual(input.Distances)
                ) && 
                (
                    this.DistancesEncoded == input.DistancesEncoded ||
                    (this.DistancesEncoded != null &&
                    this.DistancesEncoded.Equals(input.DistancesEncoded))
                ) && 
                (
                    this.TravelTimes == input.TravelTimes ||
                    this.TravelTimes != null &&
                    input.TravelTimes != null &&
                    this.TravelTimes.SequenceEqual(input.TravelTimes)
                ) && 
                (
                    this.TravelTimesEncoded == input.TravelTimesEncoded ||
                    (this.TravelTimesEncoded != null &&
                    this.TravelTimesEncoded.Equals(input.TravelTimesEncoded))
                ) && 
                (
                    this.TravelTimeProfilesEncoded == input.TravelTimeProfilesEncoded ||
                    (this.TravelTimeProfilesEncoded != null &&
                    this.TravelTimeProfilesEncoded.Equals(input.TravelTimeProfilesEncoded))
                ) && 
                (
                    this.TollCosts == input.TollCosts ||
                    this.TollCosts != null &&
                    input.TollCosts != null &&
                    this.TollCosts.SequenceEqual(input.TollCosts)
                ) && 
                (
                    this.TollCostsEncoded == input.TollCostsEncoded ||
                    (this.TollCostsEncoded != null &&
                    this.TollCostsEncoded.Equals(input.TollCostsEncoded))
                ) && 
                (
                    this.Warnings == input.Warnings ||
                    this.Warnings != null &&
                    input.Warnings != null &&
                    this.Warnings.SequenceEqual(input.Warnings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.PercentageOfDirectDistanceRelations.GetHashCode();
                if (this.Distances != null)
                    hashCode = hashCode * 59 + this.Distances.GetHashCode();
                if (this.DistancesEncoded != null)
                    hashCode = hashCode * 59 + this.DistancesEncoded.GetHashCode();
                if (this.TravelTimes != null)
                    hashCode = hashCode * 59 + this.TravelTimes.GetHashCode();
                if (this.TravelTimesEncoded != null)
                    hashCode = hashCode * 59 + this.TravelTimesEncoded.GetHashCode();
                if (this.TravelTimeProfilesEncoded != null)
                    hashCode = hashCode * 59 + this.TravelTimeProfilesEncoded.GetHashCode();
                if (this.TollCosts != null)
                    hashCode = hashCode * 59 + this.TollCosts.GetHashCode();
                if (this.TollCostsEncoded != null)
                    hashCode = hashCode * 59 + this.TollCostsEncoded.GetHashCode();
                if (this.Warnings != null)
                    hashCode = hashCode * 59 + this.Warnings.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PercentageOfDirectDistanceRelations (double) maximum
            if(this.PercentageOfDirectDistanceRelations > (double)100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PercentageOfDirectDistanceRelations, must be a value less than or equal to 100.", new [] { "PercentageOfDirectDistanceRelations" });
            }

            // PercentageOfDirectDistanceRelations (double) minimum
            if(this.PercentageOfDirectDistanceRelations < (double)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PercentageOfDirectDistanceRelations, must be a value greater than or equal to 0.", new [] { "PercentageOfDirectDistanceRelations" });
            }

            yield break;
        }
    }

}
