/* tslint:disable */
/* eslint-disable */
/**
 * Matrix Routing
 * With the Matrix Routing service you can compute distances and travel times between a set of origins and destinations.
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Warning,
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './';

/**
 * 
 * @export
 * @interface MatrixResponse
 */
export interface MatrixResponse {
    /**
     * Percentage of relations in the distance matrix which has not been calculated successfully. 
     * Zero distances corresponding to A-A relations are not included in this calculation.
     * @type {number}
     * @memberof MatrixResponse
     */
    percentageOfDirectDistanceRelations?: number;
    /**
     * The distances of the requested matrix elements [m]. To access to the distance of the relation between the origin i and the destination j, read the k-th element defined by `k = i * N + j`, with N being the number of destinations.
     * Please note that the distance for an A-A relation is always set to zero.
     * @type {Array<number>}
     * @memberof MatrixResponse
     */
    distances?: Array<number>;
    /**
     * The distances of the requested matrix elements [m]. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information.
     * To access to the distance of the relation between the origin i and the destination j, read the k-th element defined by `k = i * N + j`, with N being the number of destinations.
     * Please note that the distance for an A-A relation is always set to zero.
     * @type {string}
     * @memberof MatrixResponse
     */
    distancesEncoded?: string;
    /**
     * The travel times of the requested matrix elements [s]. To access to the travel time of the relation between the origin i and the destination j, read the k-th element defined by `k = i * N + j`, with N being the number of destinations.
     * Please note that the travel time for an A-A relation is always set to zero.
     * @type {Array<number>}
     * @memberof MatrixResponse
     */
    travelTimes?: Array<number>;
    /**
     * The travel times of the requested matrix elements [s]. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information.
     * To access to the travel time of the relation between the origin i and the destination j, read the k-th element defined by `k = i * N + j`, with N being the number of destinations.
     * Please note that the travel time for an A-A relation is always set to zero.
     * @type {string}
     * @memberof MatrixResponse
     */
    travelTimesEncoded?: string;
    /**
     * The travel time profiles of the requested matrix elements. Each profile is expressed using a encoded format which is explained [here](./documentation/matrix-routing-api/concepts/results-representation). 
     * Please note that the travel time for an A-A relation is always set to zero.
     * @type {string}
     * @memberof MatrixResponse
     */
    travelTimeProfilesEncoded?: string;
    /**
     * The toll costs of the requested matrix elements in the requested currency. To access to the toll cost of the relation between the origin i and the destination j, read the k-th element defined by `k = i * N + j`, with N being the number of destinations.  
     * Toll prices do not include VAT.
     * @type {Array<number>}
     * @memberof MatrixResponse
     */
    tollCosts?: Array<number>;
    /**
     * The toll costs of the requested matrix elements in the requested currency. Each value is expressed as unsigned integer and uses a 4-bytes little endian scheme. See [here](./documentation/matrix-routing-api/concepts/results-representation) for more information.
     * To access to the toll cost of the relation between the origin i and the destination j, read the k-th element defined by `k = i * N + j`, with N being the number of destinations.
     * Please note that the travel time for an A-A relation is always set to zero.
     * @type {string}
     * @memberof MatrixResponse
     */
    tollCostsEncoded?: string;
    /**
     * A list of warnings concerning the validity of the result.
     * @type {Array<Warning>}
     * @memberof MatrixResponse
     */
    warnings?: Array<Warning>;
}

export function MatrixResponseFromJSON(json: any): MatrixResponse {
    return MatrixResponseFromJSONTyped(json, false);
}

export function MatrixResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatrixResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'percentageOfDirectDistanceRelations': !exists(json, 'percentageOfDirectDistanceRelations') ? undefined : json['percentageOfDirectDistanceRelations'],
        'distances': !exists(json, 'distances') ? undefined : json['distances'],
        'distancesEncoded': !exists(json, 'distancesEncoded') ? undefined : json['distancesEncoded'],
        'travelTimes': !exists(json, 'travelTimes') ? undefined : json['travelTimes'],
        'travelTimesEncoded': !exists(json, 'travelTimesEncoded') ? undefined : json['travelTimesEncoded'],
        'travelTimeProfilesEncoded': !exists(json, 'travelTimeProfilesEncoded') ? undefined : json['travelTimeProfilesEncoded'],
        'tollCosts': !exists(json, 'tollCosts') ? undefined : json['tollCosts'],
        'tollCostsEncoded': !exists(json, 'tollCostsEncoded') ? undefined : json['tollCostsEncoded'],
        'warnings': !exists(json, 'warnings') ? undefined : ((json['warnings'] as Array<any>).map(WarningFromJSON)),
    };
}

export function MatrixResponseToJSON(value?: MatrixResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'percentageOfDirectDistanceRelations': value.percentageOfDirectDistanceRelations,
        'distances': value.distances,
        'distancesEncoded': value.distancesEncoded,
        'travelTimes': value.travelTimes,
        'travelTimesEncoded': value.travelTimesEncoded,
        'travelTimeProfilesEncoded': value.travelTimeProfilesEncoded,
        'tollCosts': value.tollCosts,
        'tollCostsEncoded': value.tollCostsEncoded,
        'warnings': value.warnings === undefined ? undefined : ((value.warnings as Array<any>).map(WarningToJSON)),
    };
}


